[package]
name = "minigrep"
version = "0.1.0"
edition = "2024"
description = "A simple command-line search tool"
license = "MIT OR Apache-2.0"

[[bin]]
name = "minigrep"
path = "src/main.rs"

[dependencies]
